### ISSUE TITLE
recipes?

### ISSUE THREAD

**Issue by ototinho** [waddon1/Technical-Electrical-Final-Frontiers#2] opened 2023-10-09 04:24 UTC
I just want to know why rei is only showing liquids for me, i already tried changing some configs but it seems like there's only liquids for some reson, i can see recipes for items using r and u but i cant search for anything else but liquids

**Comment by waddon1** [comment] 2023-10-09 10:09
It happens sometimes I'm working on it if you go into REI advanced settings and reload plugins the recipes should come back

**Comment by ototinho** [comment] 2023-10-09 17:08
it worked! thanks!

**Comment by waddon1** [comment] 2023-10-16 15:08
This may be fixed in the new version I haven't seen it happen in a while.

**Comment by ototinho** [comment] 2023-10-17 00:26
well, every time I enter in a world I need to reload the plugins, also i found another weird bug, for some reason portals aren`t working right, everytime i go trough a portal it spawns another portal even if i already had one, this is happening with nether and aether portals
![imagem_2023-10-16_212534773](https://github.com/waddon1/Technical-Electrical/assets/64162392/06cade32-f728-45db-be01-5ef8dcde9b8d)

**Comment by waddon1** [comment] 2023-10-17 00:34
The portal issue was fixed a while ago unless I've somehow readded it.

**Comment by waddon1** [comment] 2023-10-17 00:47
I've just tested on the latest version and I'm unable to reproduce the portal issue.

**Comment by ototinho** [comment] 2023-10-17 02:12
hm, i think my pack is outdated then

**Comment by ototinho** [comment] 2023-10-17 02:28
I just realised that i was in version 3.0.3 and when I updated all my problems went away, Im just sorry for wasting your time

**Comment by ototinho** [comment] 2023-10-17 02:28
like, really really sorry

**Comment by waddon1** [comment] 2023-10-17 12:06
It's fine

**Closed as completed by waddon1** 2023-10-17 12:06 UTC
